### ISSUE TITLE
about results of Adobe

### ISSUE THREAD

**Issue by hityzy1122** [JihyongOh/XVFI#11]
Hi, thanks for your code, could you provide the test clips you used in the paper for adobe240, thanks!

**Comment by hjSim** [comment]
Hi @YU-Zhiyang 
Can you give me your email address? We will provide you the test split of Adobe240 we used for test phase.

**Comment by YU-Zhiyang** [comment]
自动回复:邮件已收到

**Comment by YU-Zhiyang** [comment]
> Hi @YU-Zhiyang Can you give me your email address? We will provide you the test split of Adobe240 we used for test phase.

oceanyu1122@gmail.com
Thanks!
