### ISSUE TITLE
can't download dataset successfully

### ISSUE THREAD

**Issue by zhouzhengguang** [JihyongOh/XVFI#13]
Thank you for sharing your code! 
When i try to download your training dataset in https://www.dropbox.com/sh/duisote638etlv2/AABJw5Vygk94AWjGM4Se0Goza?dl=0&preview=encoded_train.tar.gz，I cannot get it successfully.
1) I tried to download it in chrome directly, after it finished,  but when i try to "tar zxvf encoded_train.tar.gz", it said "gzip: stdin: unexpected end of file. tar: Unexpected EOF in archive. tar: Unexpected EOF in archive  tar: Error is not recoverable: exiting now". then i check the size of the tar, only 6.2GB not 14GB, this method is not working.
2) Then I tried to use wget do download dataset, but it always stopped in the middle of progressbar, I think the server of dropbox is not stability.

So, could you tell me how i can download dataset successfully? or would you mind make a copy and put it to Google drive or baidu cloud disk?
Thank you very much!

**Comment by hjSim** [comment]
Hi @zhouzhengguang 
We also have experienced similar problems. 
Can you try to clear browser cache? 
[https://websetnet.net/there-was-an-error-downloading-the-file-in-dropbox-solved/](https://websetnet.net/there-was-an-error-downloading-the-file-in-dropbox-solved/)
Here is the link. Please follow the 3rd one of the link to solve the problem.

**Comment by zhouzhengguang** [comment]
Thanks for your advice! but it did't work for me.
then I changed another wifi and used "wget -c -O all.tar.gz  "https://www.dropbox.com/sh/duisote638etlv2/AABJw5Vygk94AWjGM4Se0Goza?dl=0&preview=encoded_train.tar.gz?dl=1"" to download datasets successfully.

**Comment by ZXMMD** [comment]
> Thanks for your advice! but it did't work for me. then I changed another wifi and used "wget -c -O all.tar.gz "https://www.dropbox.com/sh/duisote638etlv2/AABJw5Vygk94AWjGM4Se0Goza?dl=0&preview=encoded_train.tar.gz?dl=1"" to download datasets successfully.

I encountered a problem downloading the dataset. Can you upload the training set to Baidu Cloud Disk? Thank you so much!
