### ISSUE TITLE
Have interpolated frames go into separate folder?

### ISSUE THREAD

**Issue by dillfrescott** [JihyongOh/XVFI#15]
How would I go about doing this? Its putting the interpolated frames into the same folder as the originals

**Comment by JihyongOh** [comment]
@dillfrescott If you want it, you can replace It_Path[0] of this [line](https://github.com/JihyongOh/XVFI/blob/1352a13d0fe01226a6d893b6b94181606c8e14f4/main.py#L404) with your own path.

**Comment by jreoka** [comment]
Ok thank you!
