### ISSUE TITLE
Can not download the pretrianed models from Dropbox~

### ISSUE THREAD

**Issue by liangyang-mt** [JihyongOh/XVFI#16]
Hi, thank you for your open source, I found that the pretrained model can not be downloaded from the dropbox, and it may be the problem of internet's firewall. Could you please to upload pretrained models in other tools (like one-drive or baidu netdisk)? looking forward to your reply~

**Comment by JihyongOh** [comment]
@liangyang-mt 
Hi, here are two checkpoints for [X-Train](https://1drv.ms/u/s!Alb09xi2K8SjgtgUbmFvzfIO4ez3Tw?e=EMHPT6)- and [Vimeo90K](https://1drv.ms/u/s!Alb09xi2K8SjgtgVMR1HQYhjQQM7qA?e=ZbqlP5)-pretrained versions provided by one-drive.
If they don't work on your server, please tell me with your private email.
Thank you.
