### ISSUE TITLE
[Dataset] The link of X4K1000FPS has expired.

### ISSUE THREAD

**Issue by NK-CS-ZZL** [JihyongOh/XVFI#17]
The [link](https://www.dropbox.com/s/tjmxauo05axoi5v/png_test_8_input_frames.zip?dl=0) given in README has expired and the dataset is no longer available. I hope the authors could update a new link for followers.

**Comment by JihyongOh** [comment]
@NK-CS-ZZL, 
Hi, thank you for noticing. We have fixed it, could you check it?

**Comment by NK-CS-ZZL** [comment]
The new one is good. Thank for your reply and I'll close the issue.
