### ISSUE TITLE
A dataset question

### ISSUE THREAD

**Issue by syd1997** [JihyongOh/XVFI#8]
i have downloaded the X4K1000FPS dataset from your link. however the data in subfolder is in .mp4 format, but in your readme.md you showed that in .png format.How can i convert the dataset in .mp4 format to .png format.
the error isfollowing
![image](https://user-images.githubusercontent.com/74699222/131056150-5f5104ce-cd11-4f8c-885a-1ed7f111c71e.png)
and when i found that the module that make the train set doesn't work.
![image](https://user-images.githubusercontent.com/74699222/131056242-f6aded50-8a78-4268-9678-431aac816bf1.png)
when printing the sample_path, it tell me that: 'sample_paths=[]' which means sample_path is empty.

**Comment by syd1997** [comment]
when i download code, and test it directly, it also told me a runtime error:
![image](https://user-images.githubusercontent.com/74699222/131064477-beeccb5a-dad0-4f6f-9a92-6e4a98da3c95.png)
i have checked the dataset root.
![image](https://user-images.githubusercontent.com/74699222/131064615-9ab4d8e2-bede-4d59-8208-b8cd13e69a24.png)
![image](https://user-images.githubusercontent.com/74699222/131064660-cefa56ec-3a4e-4ed4-b3bd-b3efa526f89d.png)

**Comment by hjSim** [comment]
@dietmoutaindew 
You can find 'mp4_decoding.py' file in the zip file downloaded from Dropbox link. This will decode mp4 files into png files in appropriate directories.
Please run the 'mp4_decoding.py' and let us know if it works or not!

**Comment by syd1997** [comment]
@JihyongOh 
Hey! Much thanks for your reply! I have solved the problem with your help!
Thanks a lot!
